### ISSUE TITLE
beforeSend callback is not called for cached events after going from offline mode to online mode

### ISSUE THREAD

**Issue by hgadalrab** [getsentry/sentry-dart#2034]
### Platform

Flutter Mobile

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.4.1 23E224 darwin-arm64, locale en-AT)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] Connected device (5 available)            
    ! Error: Browsing on the local area network for M’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!

### Version

8.1.0

### Steps to Reproduce

1. add beforeSend callback to the options
2. switch to offline mode 
3. send event
4. beforeSend is called but the request fails due to the network connection
5. switch to online mode

---- Code ---- 
 await SentryFlutter.init((options) {
    options
      ..dsn = dsn
      ..addIntegration(LoggingIntegration(minEventLevel: Level.WARNING))
      ..beforeSend = ((event, hint) {
        print('Sending event with id ${event.eventId} and message: ${event.message?.formatted}');
        return event;
      });
  });

  Timer.periodic(const Duration(seconds: 5), (timer) {
    logger.warning('Sending event At ${DateTime.now()}');
  });

### Expected Result

beforeSend is called before the request is sent to Sentry

### Actual Result

beforeSend is not called and the request is sent to Sentry

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
hi thanks for raising this, we'll have a look

**Comment by denrase** [comment]
The `beforeSend` callback is the last place where you can mutate or drop events before they are being sent to sentry.  See [Filtering Error Events](https://docs.sentry.io/platforms/flutter/configuration/filtering/#filtering-error-events) for more info.

On Flutter event is sent through the iOS & Android native SDKs. To my knowledge, we will drop an event if it fails to send due to a lack of connection. Maybe @philipphofmann has some insight into how iOS is handling connection failures?

In any case, calling `beforeSend` again is not correct, as its intent is to either modify or drop an event before sending it to Sentry.

**Comment by philipphofmann** [comment]
That is intended behavior. SDKs only call the beforeSend callback once. It's meant to modify the event before the SDKs send it to Sentry. Users don't have to worry about their apps being online or offline. SDKs ensure to send events to sentry once apps are online again.

Why do you expect the SDK to call beforeSend again when the device is online again @hgadalrab?

**Comment by hgadalrab** [comment]
@philipphofmann Due to this issue  https://github.com/getsentry/sentry-dart/issues/1753, I had so many cached events which are also too old. I couldn't find another way to drop these events except for this callback, which, I think, should be called before sending to Sentry for the second time.

**Comment by vaind** [comment]
I believe you can have a one-time code to empty the cache directory from within your app code (you can check file times). The linked issue should be fixed since v8.

**Comment by hgadalrab** [comment]
The linked issue is fixed in v8, yes, but the fix doesn't apply to the old events. So,  if I had 100 events, and updated to v8, the 100 events will be kept in the cache. 

If there is no other solution provided by Sentry, I will have to do this, but I expected a better solution e.g, the beforeSend callback or providing access to the existing events.

**Comment by buenaflor** [comment]
> I believe you can have a one-time code to empty the cache directory from within your app code

Unfortunately I believe this is the only solution we can currently offer currently

**Comment by philipphofmann** [comment]
> So, if I had 100 events, and updated to v8, the 100 events will be kept in the cache.

@buenaflor, can't we do some simple logic to check for old events in that cache and delete them? I guess more people could run into that problem.

**Comment by hgadalrab** [comment]
@buenaflor Although it would be good to have a callback every time the event is sent to Sentry, but it would also be nice to have what you suggested. @philipphofmann

**Comment by buenaflor** [comment]
Would you have an idea of the size of scope of this? @denrase

**Comment by hgadalrab** [comment]
Is there going to be a fix for this soon or shouldn't I wait and have my own fix? @buenaflor

**Comment by buenaflor** [comment]
It'd be great if you could create your own fix. I can't give a timeline when we could get to this issue

**Comment by buenaflor** [comment]
Closing this now as it's possible to empty the cache directory and it's fixed in v8 generally

**Comment by mfrischbutter** [comment]
@buenaflor the issue still persists in v8.9.0. The callback is not called for cached events.
My sentry is flooded with SocketException errors. And i was still able to reproduce this error locally. 

```
 ..beforeSend = (event, hint) {
          if (event.throwable is DioException) {
            final dioError = event.throwable as DioException;
            if (dioError.error is SocketException) {
              return null;
            }
            if (dioError.response?.statusCode == 500 ||
                dioError.response?.statusCode == 503 ||
                dioError.response?.statusCode == 400) {
              // add more context to the event
              event.contexts['dio'] = {
                'response': dioError.response?.data,
                'request': dioError.requestOptions,
              };
            }
          }
          // Return the event as-is for all other cases
          return event;
        };
```

**Comment by denrase** [comment]
@mfrischbutter I added your sample code and for me it works as expected. When there is a SocketException in dio, we catch it in beforeSend and filter it out, so it is never passed to the native SDK.

| BeforeSend | Dropped |
| -- | -- |
| ![Image](https://github.com/user-attachments/assets/59cae9fe-6bd5-47c7-b984-c7dc3cb4802d) | ![Image](https://github.com/user-attachments/assets/ba267118-254b-4768-a99f-60c5e9a50200) |


Could you provide more info into how to reproduce your issue what your expected outcome is and what the actual outcome is?

**Comment by zhao0** [comment]
In my case, `beforeSend` will not call  if I call `Sentry.captureException(error, stackTrace: stackTrace);` directly.
