### ISSUE TITLE
C++ files are semantically incorrect with respect to the latest Xcode16.3 definitions.

### ISSUE THREAD

**Issue by KumarArab** [getsentry/sentry-dart#2838]
### Platform

Flutter Mobile iOS

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

> Semantic Issue (Xcode): Static assertion failed due to requirement '!is_const<const
sentry::profiling::ThreadMetadataCache::ThreadHandleMetadataPair>::value': std::allocator does not support
const types
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
or18.4.sdk/usr/include/c++/v1/__memory/allocator.h:94:16

>Semantic Issue (Xcode): Static assertion failed due to requirement 'is_same<std::allocator<const
sentry::profiling::ThreadMetadataCache::ThreadHandleMetadataPair>, std::allocator<int>>::value':
[allocator.requirements] states that rebinding an allocator to the same type should result in the original
allocator
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
or18.4.sdk/usr/include/c++/v1/__memory/allocator_traits.h:377:16

>Semantic Issue (Xcode): No type named 'value_type' in 'std::allocator<const
sentry::profiling::ThreadMetadataCache::ThreadHandleMetadataPair>'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
or18.4.sdk/usr/include/c++/v1/vector:426:49

>Semantic Issue (Xcode): No type named 'type' in 'std::enable_if<false, int>'; 'enable_if' cannot be used
to disable this declaration
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulat
or18.4.sdk/usr/include/c++/v1/__type_traits/enable_if.h:27:57

Could not build the application for the simulator.

### Version

sentry_flutter: 8.14.1

### Steps to Reproduce

Update Xcode to 16.3 and build the iOS app

### Expected Result

App should run seamlessly 

### Actual Result

Xcode unable to build the app

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
hey this should be fixed starting from Flutter `8.14.0`, I can see you're using `8.14.1`, did you clean your project as well as the pods?

**Comment by KumarArab** [comment]
It is resolved in 8.14.0+

**Comment by vasilich6107** [comment]
Seems to be still an issue

@KumarArab could you clarify how you managed to fix?

<img width="339" alt="Image" src="https://github.com/user-attachments/assets/f2d48805-4959-47c2-8fe8-8f54544b97b5" />

**Comment by theajr** [comment]
Did anyone able to fix this?

**Comment by buenaflor** [comment]
@theajr make sure to use version 8.14.0 or higher and to be sure remove your `.pub-cache` and run `flutter clean`

**Comment by buenaflor** [comment]
Make sure to run `pod update` in your ios project

**Comment by buenaflor** [comment]
Since I've seen this case now:

make sure that whatever dependency you install in your app does not include the Sentry Cocoa SDK (aside from Sentry Flutter SDK). Using Sentry within SDKs is discouraged and not recommended however we've still seen SDKs use it, specifically SDKS using older Sentry Cocoa versions which cause version conflicts with the version we install with the Sentry Flutter SDK.

**Comment by ospaarmann** [comment]
For me this helped:

- Make sure you have 8.14.0 or higher installed 
- Run these commands:

```
flutter clean
dart pub cache clean
flutter pub get
cd ios
rm Podfile.lock
pod install
cd ..
```

You will have to re-install all dependencies for all dart projects after that, so be aware of that. And think if it is a good idea to delete your Podfile.lock and make sure you have a backup or it's checked in your repo.
